### ISSUE TITLE
HttpMediaTypeNotAcceptableException Could not find acceptable representation

### ISSUE THREAD

**Issue by tigerMoon** [jmnarloch/rxjava-spring-boot-starter#2]
this is my env:
java8 , spring boot 1.2.3, spring framework 4.2.4

when i do as demo  README . it`s throw exception like this:
org.springframework.web.HttpMediaTypeNotAcceptableException: Could not find acceptable representation
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:251)
	at org.springframework.web.servlet.mvc.method.annotation.AbstractMessageConverterMethodProcessor.writeWithMessageConverters(AbstractMessageConverterMethodProcessor.java:153)
	at org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor.handleReturnValue(RequestResponseBodyMethodProcessor.java:165)
	at org.springframework.web.method.support.HandlerMethodReturnValueHandlerComposite.handleReturnValue(HandlerMethodReturnValueHandlerComposite.java:80)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:126)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:814)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:737)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:959)

**Comment by jmnarloch** [comment]
Can you please share the information how you controller looks like?

**Comment by jmnarloch** [comment]
Can you please take a look at the [Demo.java](https://github.com/jmnarloch/rxjava-spring-boot-starter/blob/master/src/test/java/io/jmnarloch/spring/boot/rxjava/Demo.java) class?

**Comment by tigerMoon** [comment]
like this : 
@RequestMapping(value = "/land", method = RequestMethod.GET,produces = MediaType.APPLICATION_JSON_UTF8_VALUE)
    public Observable<Invoice> getlandInfo(@RequestParam String enterpriseName) {
        return Observable.just(
                new Invoice("Acme", new Date()),
                new Invoice("Oceanic", new Date())
        );
    }
